## JOVIAL configuration

nginx-ingress:
  rbac:
    create: true
  controller:
    service:
      type: NodePort
      nodePorts:
        http: 30080
        https: 30443

replicaCount: 1

image:
  repository: nginx
  tag: stable
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  path: /
  hosts:
    - jovial-frontend.chivo.cl
