## JOVIAL configuration

jovial:
  kube:
    clusterDomain: cluster.local
    userHomeDirTemplate: /users/{username}
  ldap:
    address: 10.6.91.26
    port: 389
    dnTemplate: uid={username},dc=cm,dc=cluster
    useSSL: False
  hub:
    confirmNoSSL: True
    listenAddress: 0.0.0.0
    cleanupUsersOnExit: False
  spawner:
    startTimeout: 300
    httpTimeout: 600
    image:
      repository: docker-registry.chivo.cl/jovial/user
      tag: latest
      pullPolicy: Always
    extraArgs: "['--NotebookApp.iopub_data_rate_limit = 1000000000']"

deployment:
  replicaCount: 3
  image:
    repository: docker-registry.chivo.cl/jovial/hub
    tag: latest
    pullPolicy: IfNotPresent
  ports:
    frontend: 8000
    proxy: 8001
    rest: 8081
  command: ["/bin/bash", "-c", "jupyterhub -f /config/JOVIAL_config.py"]
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "route"
    nginx.ingress.kubernetes.io/session-cookie-hash: "sha1"
  host: jovial.chivo.cl

## nginx-ingress dependency configuration

nginx-ingress:
  rbac:
    create: true
  controller:
    service:
      type: NodePort
      nodePorts:
        http: 30080
        https: 30443
