## JOVIAL configuration

deployment:
  replicaCount: 1
  image:
    repository: docker-registry.chivo.cl/jovial/hub
    tag: stable
    pullPolicy: IfNotPresent
  command: ["/bin/bash", "-c", "jupyterhub -f /JOVIAL_config.py"]
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  path: /
  hosts:
    - jovial-frontend.chivo.cl

## nginx-ingress dependency configuration

nginx-ingress:
  rbac:
    create: true
  controller:
    service:
      type: NodePort
      nodePorts:
        http: 30080
        https: 30443
