kind: Namespace
apiVersion: v1
metadata:
  name: jovial
  labels:
    name: jovial
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jovial
  namespace: jovial
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: jovial
  name: jovial-deployment-role
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: jovial-rolebinding
  namespace: jovial
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jovial-deployment-role
subjects:
- kind: ServiceAccount
  name: jovial
  namespace: jovial

