FROM jupyterhub/jupyterhub:0.8.1
RUN pip install git+https://github.com/ChileanVirtualObservatory/ldapauthenticator.git
RUN pip install git+https://github.com/jupyterhub/kubespawner
RUN pip install mysqldb