apiVersion: v1
kind: Service
metadata:
  name: {{ template "jovial.fullname" . }}-external
  labels:
    app: {{ template "jovial.name" . }}
    chart: {{ template "jovial.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.jovial.kubernetes.deployment.ports.frontend }}
      targetPort: frontend
      protocol: TCP
      name: frontend
  selector:
    app: {{ template "jovial.name" . }}
    release: {{ .Release.Name }}
