apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "jovial.fullname" . }}-hubdb
  labels:
    app: {{ template "jovial.name" . }}
    chart: {{ template "jovial.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: jovialdb
spec:
  selector:
    matchLabels:
      app: {{ template "jovial.name" . }}
      chart: {{ template "jovial.chart" . }}
      release: {{ .Release.Name }}
      heritage: {{ .Release.Service }}
      component: jovialdb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ template "jovial.name" . }}
        chart: {{ template "jovial.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
        component: jovialdb
    spec:
      containers:
      - image: mysql:5.7.22
        name: mysql
        env:
        - name: MYSQL_RANDOM_ROOT_PASSWORD
          value: 'yes'
        - name: MYSQL_DATABASE
          value: 'jovial'
        - name: MYSQL_USER
          value: jovial
        - name: MYSQL_PASSWORD
          value: {{ .Values.hub.db.password }}
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: {{ template "jovial.fullname" . }}-hubdb-pvc