{{- if .Values.k8s.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "jovial.fullname" . }}
  labels:
    app: {{ template "jovial.name" . }}
    chart: {{ template "jovial.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: {{ .Values.k8s.ingress.domain }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ template "jovial.fullname" . }}-external
              servicePort: frontend
{{- end}}
