{{- if .Values.jovial.kubernetes.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "jovial.fullname" . }}
  labels:
    app: {{ template "jovial.name" . }}
    chart: {{ template "jovial.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "lbroute"
    nginx.ingress.kubernetes.io/session-cookie-hash: "sha1"
spec:
  rules:
    - host: {{ .Values.jovial.kubernetes.ingress.domain }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ template "jovial.fullname" . }}-external
              servicePort: frontend
{{- end}}
