apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "jovial.fullname" . }}-config
  labels:
    app: {{ template "jovial.name" . }}
    chart: {{ template "jovial.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  JOVIAL_config.py: |
    import socket
    import re

    config = get_config()
    # Since helm translates 'True' to 'true' and 'False' to 'false' we need this so we don't get python 'NameErrors'
    false = False
    true = True

    # JupyterHub Settings ----------------------------------------------------------

    config.JupyterHub.authenticator_class = 'ldapauthenticator.LDAPAuthenticator'
    config.JupyterHub.spawner_class = 'kubespawner.KubeSpawner'
    config.JupyterHub.extra_log_file = '/var/log/jupyterhub'
    config.JupyterHub.ip = '{{ .Values.jovial.hub.listenAddress }}'
    config.JupyterHub.hub_ip = '{{ .Values.jovial.hub.listenAddress }}'
    config.JupyterHub.confirm_no_ssl = {{ .Values.jovial.hub.confirmNoSSL }}
    config.JupyterHub.cleanup_servers = {{ .Values.jovial.hub.cleanupUsersOnExit }}

    # LDAP Settings ----------------------------------------------------------------

    config.LDAPAuthenticator.server_address = '{{ .Values.jovial.ldap.address }}'
    config.LDAPAuthenticator.server_port = {{ .Values.jovial.ldap.port }}
    config.LDAPAuthenticator.use_ssl = {{ .Values.jovial.ldap.useSSL }}
    config.LDAPAuthenticator.bind_dn_template = '{{ .Values.jovial.ldap.dnTemplate }}'
    config.PAMAuthenticator.open_sessions = False

    # KubeSpawner Settings ---------------------------------------------------------

    config.KubeSpawner.namespace = '{{ .Release.Namespace }}'
    config.KubeSpawner.start_timeout = {{ .Values.jovial.spawner.startTimeout }}
    config.KubeSpawner.pod_name_template = '{{ .Values.jovial.spawner.podNameTemplate }}'
    config.KubeSpawner.singleuser_image_spec = '{{ .Values.jovial.spawner.image.repository }}:{{ .Values.jovial.spawner.image.tag }}'
    config.KubeSpawner.singleuser_image_pull_policy = '{{ .Values.jovial.spawner.image.pullPolicy }}'
    config.KubeSpawner.hub_connect_ip = '{{ template "jovial.fullname" . }}-internal.{{ .Release.Namespace }}.svc.{{ .Values.jovial.kubernetes.clusterDomain }}'
    config.KubeSpawner.environment = {
            'HOME': lambda spawner: '/home/' + str(spawner.user.name),
            'USER': lambda spawner: spawner.user.name,
            'NOTEBOOK_DIR': lambda spawner: '/home/'+ str(spawner.user.name)
    }
    config.KubeSpawner.volume_mounts = [{
        'name': '{username}',
        'mountPath': '/home/{username}'
    }]
    config.KubeSpawner.volumes = [{
        'name': '{username}',
        'hostPath': {
           'path': '{{ .Values.jovial.kubernetes.userHomeDirTemplate }}'
        }
    }]
    config.KubeSpawner.singleuser_init_containers = [{
        'name': '{{ .Values.jovial.spawner.installer.name }}',
        'image': '{{ .Values.jovial.spawner.installer.image.repository }}:{{ .Values.jovial.spawner.installer.image.tag }}',
        'imagePullPolicy': '{{ .Values.jovial.spawner.installer.image.pullPolicy }}',
        'volumeMounts': [{
            'name': '{jovial-username}',
            'mountPath': '/home/{jovial-username}'
        }],
        'env': [
            {'name': 'USER', 'value': '{jovial-username}'},
            {'name': 'HOME', 'value': '/home/{jovial-username}'}
        ]
    }]

    def getLocalSpawnerIP():
      sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
      sock.connect(('kubernetes.default.svc.cluster.local', 443))
      return sock.getsockname()[0]

    def JOVIAL_ModifyPodHook(spawner, pod):
      if {{ .Values.jovial.spawner.debugMessages }}:
        spawner.log.info('[JOVIAL_ModifyPodHook]: Spawner pod internal type: ' + str(type(pod)))
        spawner.log.info('[JOVIAL_ModifyPodHook]: Replacing \'{jovial-username}\' with \'' + str(spawner.user.name) + '\' in the \'initContainers\' section of the pod')
      container = pod.spec.init_containers[0]
      if {{ .Values.jovial.spawner.debugMessages }}:
        spawner.log.info('[JOVIAL_ModifyPodHook]: initContainer type: ' + str(type(container)))
        spawner.log.info('[JOVIAL_ModifyPodHook]: initContainer Before: ' + str(container))
      container['volumeMounts'][0]['name'] = container['volumeMounts'][0]['name'].replace('{jovial-username}', spawner.user.name)
      container['volumeMounts'][0]['mountPath'] = container['volumeMounts'][0]['mountPath'].replace('{jovial-username}', spawner.user.name)
      container['env'][0]['value'] = container['env'][0]['value'].replace('{jovial-username}', spawner.user.name)
      container['env'][1]['value'] = container['env'][1]['value'].replace('{jovial-username}', spawner.user.name)
      if {{ .Values.jovial.spawner.debugMessages }}:
        spawner.log.info('[JOVIAL_ModifyPodHook]: initContainer After: ' + str(container))
      containerEnv = pod.spec.containers[0].env
      index = -1
      for i, var in enumerate(containerEnv):
         if var.name == 'JUPYTERHUB_API_URL':
             index = i
             break
      if {{ .Values.jovial.spawner.debugMessages }}:
        spawner.log.info('[JOVIAL_ModifyPodHook]: JUPYTERHUB_API_URL Before: ' + str(containerEnv[index].value))
      pattern = re.compile('http:\/\/(.*):8081\/hub\/api')
      result = pattern.search(containerEnv[index].value)
      to_replace = result.group(1)
      spawner_ip = getLocalSpawnerIP()
      if {{ .Values.jovial.spawner.debugMessages }}:
        spawner.log.info('[JOVIAL_ModifyPodHook]: Replacing ' + to_replace + ' with ' + spawner_ip)
      containerEnv[index].value = containerEnv[index].value.replace(to_replace, spawner_ip)
      if {{ .Values.jovial.spawner.debugMessages }}:
        spawner.log.info('[JOVIAL_ModifyPodHook]: JUPYTERHUB_API_URL After: ' + str(containerEnv[index].value))
      extra_args = dict()
      extra_args['name'] = 'JOVIAL_NOTEBOOK_EXTRA_ARGS'
      extra_args['value'] = '{{ .Values.jovial.spawner.extraArgs }}'
      containerEnv.append(extra_args)
      if {{ .Values.jovial.spawner.debugMessages }}:
        spawner.log.info('[JOVIAL_ModifyPodHook]: ENV: ' + str(containerEnv))
      pod.spec.containers[0].working_dir = '/home/' + spawner.user.name
      return pod

    config.KubeSpawner.modify_pod_hook = JOVIAL_ModifyPodHook
