apiVersion: v1
kind: Service
metadata:
  name: jupyterhub-external
  namespace: jovial
  labels:
    app: jovial-deployment
spec:
  type: NodePort
  selector:
    app: jovial-deployment
  ports:
  - name: hub-ui
    port: 8000
    nodePort: 30000
  clusterIP: 10.100.0.1
