apiVersion: v1
kind: Service
metadata:
  name: jupyterhub-external
  namespace: jovial
  labels:
    app: jovial-deployment
spec:
  type: NodePort
  selector:
    app: jovial-deployment
  ports:
  - name: hub-ui
    port: 8000
    nodePort: 30000
  clusterIP: 10.100.0.1
---
apiVersion: v1
kind: Service
metadata:
  name: jupyterhub-internal
  namespace: jovial
  labels:
    app: jovial-deployment
spec:
  type: ClusterIP
  selector:
    app: jovial-deployment
  ports:
  - name: hub-api
    protocol: TCP
    port: 8081
    targetPort: 8081
  - name: proxy-api
    protocol: TCP
    port: 8001
    targetPort: 8001
  clusterIP: 10.100.0.2
