apiVersion: v1
kind: Service
metadata:
  name: jupyterhub-external
  namespace: jovial
  labels:
    app: jovial-deployment
spec:
  type: NodePort
  selector:
    app: jovial-deployment
  ports:
  - name: hub-ui
    port: 8000
    nodePort: 30000
  clusterIP: 10.100.0.1
---
apiVersion: v1
kind: Service
metadata:
  name: jupyterhub-internal
  namespace: jovial
  labels:
    app: jovial-deployment
spec:
  type: ClusterIP
  selector:
    app: jovial-deployment
  ports:
  - name: hub-api
    protocol: TCP
    port: 8081
    targetPort: 8081
  - name: proxy-api
    protocol: TCP
    port: 8001
    targetPort: 8001
  clusterIP: 10.100.0.2
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jovialhub
  namespace: jovial
  labels:
    app: jovial-deployment
spec:
  replicas: 1 
  template:
    metadata:
      namespace: jovial
      labels:
        app: jovial-deployment
    spec:
      containers:
      - name: jupyterhub
        image: 10.100.0.3:5000/jovial/hub
        ports:
        - name: hub-ui
          containerPort: 8000
        - name: proxy-api
          containerPort: 8001
        - name: hub-api
          containerPort: 8081
        command: ["/bin/bash", "-c", "jupyterhub -f /jupyterhub_config.py"]
        volumeMounts:
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: jovial-api-token
          readOnly: true
      volumes:
      - name: jovial-api-token
        secret:
          secretName: jovial-token-m90rs
