# JOVIAL Configuration Options

k8s:
  domain: cluster.local
  deploy:
    replicas: 3
    minAvailable: 2
    image: docker.chivo.cl/jovial/hub:latest
    ports:
      frontend: 8000
      proxy: 8001
      rest: 8081
  ingress:
    enabled: true
    domain: jovial.example.com

users:
  home:
    nfs:
      server: nfs.example.com
      path: /exports/users
  ldap:
    address: ldap.example.com
    port: 636
    dn: uid={username},dc=people,dc=example,dc=com
    ssl:
      enabled: true
      CACert: |
        -----BEGIN CERTIFICATE-----
        ...
        -----END CERTIFICATE-----
      clientCert: |
        -----BEGIN CERTIFICATE-----
        ...
        -----END CERTIFICATE-----
      clientKey: |
        -----BEGIN PRIVATE KEY-----
        ...
        -----END PRIVATE KEY-----
  container:
    image: docker.chivo.cl/jovial/user:latest
    extraArgs: [""]
  initContainer:
    image: docker.chivo.cl/jovial/installer:latest

hub:
  debug: false
  timeout: 1200

# nginx-ingress Dependency Configuration

nginx-ingress:
  rbac:
    create: true
  controller:
    replicaCount: 3
    minAvailable: 2
    service:
      type: ClusterIP
      clusterIP: 10.96.0.100
